# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieDB' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SDWebImage', '~> 5.0'

  # Pods for MovieDB

  target 'MovieDBTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovieDBUITests' do
    # Pods for testing
  end

end
